# Generated by Django 4.0.3 on 2022-03-26 19:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='boardFEN',
        ),
        migrations.RemoveField(
            model_name='player',
            name='moves',
        ),
        migrations.AddField(
            model_name='games',
            name='boardFEN',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='games',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='games',
            name='moves',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='games',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
